In [4]:
import pandas as pd
import numpy as np

automobile = pd.read_csv('automobile.csv')

#### Phase 1: Understand the data

In [5]:
automobile.head()

,symboling,normalized_losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheel,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450

In [6]:
automobile.shape

(201, 26)

In [7]:
automobile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized_losses  164 non-null    float64
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       199 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheel        201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               197 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    float64
 22  peak-rpm           199 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    int64
dtypes: float64(10), int64(6), object(10)
memory usage: 41.0+ KB

In [9]:
automobile.describe(include='all')

,symboling,normalized_losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheel,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,201.000000,164.000000,201,201,201,199,201,201,201,201.000000,...,201.000000,201,197.000000,197.000000,201.000000,199.000000,199.000000,201.000000,201.000000,201.000000
unique,NaN,NaN,22,2,2,2,5,3,2,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,toyota,gas,std,four,sedan,fwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,32,181,165,113,94,118,198,NaN,...,NaN,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.840796,122.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.797015,...,126.875622,NaN,3.330711,3.256904,10.164279,103.396985,5117.587940,25.179104,30.686567,13207.129353
std,1.254802,35.442168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.066366,...,41.546834,NaN,0.270793,0.319256,4.004965,37.553843,480.521824,6.423220,6.815150,7947.066342
min,-2.000000,65.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,...,61.000000,NaN,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,...,98.000000,NaN,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,115.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,...,120.000000,NaN,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,150.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,...,141.000000,NaN,3.590000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,...,326.000000,NaN,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

In [12]:
automobile.columns.tolist()

['symboling',
 'normalized_losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheel',
 'engine-location',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-type',
 'num-of-cylinders',
 'engine-size',
 'fuel-system',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg',
 'price']

#### Phase 2: find the missing values

In [15]:
automobile.isnull().sum()

(automobile == '?').sum()

symboling            0
normalized_losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheel          0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [18]:
missing_report = pd.DataFrame({
    "missing_nan": automobile.isna().sum(),
    # "missing_quesiton_mark": automobile.eq('?').sum()
    "missing_question_mark": (automobile == '?').sum()
})

print(missing_report)

                   missing_nan  missing_question_mark
symboling                    0                      0
normalized_losses           37                      0
make                         0                      0
fuel-type                    0                      0
aspiration                   0                      0
num-of-doors                 2                      0
body-style                   0                      0
drive-wheel                  0                      0
engine-location              0                      0
wheel-base                   0                      0
length                       0                      0
width                        0                      0
height                       0                      0
curb-weight                  0                      0
engine-type                  0                      0
num-of-cylinders             0                      0
engine-size                  0                      0
fuel-system                  0                      0
bore                         4                      0
stroke                       4                      0
compression-ratio            0                      0
horsepower                   2                      0
peak-rpm                     2                      0
city-mpg                     0                      0
highway-mpg                  0                      0
price                        0                      0

#### Phase 3: Understand the Categorical Columns

In [19]:
automobile.head(3)

,symboling,normalized_losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheel,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500

In [20]:
automobile['body-style'].value_counts()

body-style
sedan          94
hatchback      68
wagon          25
hardtop         8
convertible     6
Name: count, dtype: int64

In [22]:
automobile[['body-style', 'fuel-system']].value_counts()

body-style   fuel-system
sedan        mpfi           48
hatchback    2bbl           28
sedan        2bbl           26
hatchback    mpfi           20
sedan        idi            15
wagon        mpfi           12
             2bbl            9
hatchback    spdi            7
             1bbl            7
hardtop      mpfi            6
convertible  mpfi            6
sedan        1bbl            3
hatchback    4bbl            3
wagon        idi             3
sedan        spdi            2
hatchback    mfi             1
             idi             1
hardtop      2bbl            1
hatchback    spfi            1
wagon        1bbl            1
hardtop      idi             1
Name: count, dtype: int64

In [23]:
automobile['aspiration'].value_counts()

aspiration
std      165
turbo     36
Name: count, dtype: int64

In [25]:
automobile['num-of-doors'].value_counts()

num-of-doors
four    113
two      86
Name: count, dtype: int64

In [27]:
automobile.duplicated().sum()

0

#### Let's make the column header small letter and a-a to a_a

In [30]:
automobile.columns = (
    automobile.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "", regex=False)
    .str.replace("-", "_", regex=False)
)

automobile.columns.tolist()

['symboling',
 'normalized_losses',
 'make',
 'fuel_type',
 'aspiration',
 'num_of_doors',
 'body_style',
 'drive_wheel',
 'engine_location',
 'wheel_base',
 'length',
 'width',
 'height',
 'curb_weight',
 'engine_type',
 'num_of_cylinders',
 'engine_size',
 'fuel_system',
 'bore',
 'stroke',
 'compression_ratio',
 'horsepower',
 'peak_rpm',
 'city_mpg',
 'highway_mpg',
 'price']

#### Phase 4: Check the data types

In [31]:
automobile.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_of_doors          object
body_style            object
drive_wheel           object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_of_cylinders      object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                  int64
dtype: object

#### Phase 7: Convert it into numeric columns

In [33]:
numeric_columns = [
    "normalized_losses",
    "wheel_base",
    "length",
    "width",
    "height",
    "curb_weight",
    "engine_size",
    "bore",
    "stroke",
    "compression_ratio",
    "horsepower",
    "peak_rpm",
    "city_mpg",
    "highway_mpg",
    "price"
]

for col in numeric_columns:
    automobile[col] = pd.to_numeric(automobile[col], errors='coerce')

automobile[numeric_columns].dtypes

normalized_losses    float64
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_size            int64
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                  int64
dtype: object

#### Phase 8: Handle the Missing Value

In [ ]:
automobile.isnull()