In [88]:
import pandas as pd

df = pd.read_csv("pokemon.csv")

In [89]:
df.head()

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special-attack,special-defense
0,1,bulbasaur,1,0.7,6.9,64,grass,poison,45,49,49,45,65,65
1,2,ivysaur,1,1.0,13.0,142,grass,poison,60,62,63,60,80,80
2,3,venusaur,1,2.0,100.0,236,grass,poison,80,82,83,80,100,100
3,4,charmander,1,0.6,8.5,62,fire,NaN,39,52,43,65,60,50
4,5,charmeleon,1,1.1,19.0,142,fire,NaN,58,64,58,80,80,65

In [90]:
df.shape

(807, 14)

In [91]:
df.columns

Index(['id', 'species', 'generation_id', 'height', 'weight', 'base_experience',
       'type_1', 'type_2', 'hp', 'attack', 'defense', 'speed',
       'special-attack', 'special-defense'],
      dtype='object')

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 807 entries, 0 to 806
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               807 non-null    int64
 1   species          807 non-null    object
 2   generation_id    807 non-null    int64
 3   height           807 non-null    float64
 4   weight           807 non-null    float64
 5   base_experience  807 non-null    int64
 6   type_1           807 non-null    object
 7   type_2           405 non-null    object
 8   hp               807 non-null    int64
 9   attack           807 non-null    int64
 10  defense          807 non-null    int64
 11  speed            807 non-null    int64
 12  special-attack   807 non-null    int64
 13  special-defense  807 non-null    int64
dtypes: float64(2), int64(9), object(3)
memory usage: 88.4+ KB

In [93]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace("**", "", regex=False)
    .str.replace("-", "_", regex=False)
    .str.replace(" ", "_", regex=False)
)

print(df.columns.tolist())

['id', 'species', 'generation_id', 'height', 'weight', 'base_experience', 'type_1', 'type_2', 'hp', 'attack', 'defense', 'speed', 'special_attack', 'special_defense']

In [94]:
# Selecting columns
df[['height', 'weight', 'speed']]

     height  weight  speed
0       0.7     6.9     45
1       1.0    13.0     60
2       2.0   100.0     80
3       0.6     8.5     65
4       1.1    19.0     80
..      ...     ...    ...
802     0.6     1.8     73
803     3.6   150.0    121
804     5.5   820.0     13
805     1.8    13.0    107
806     1.5    44.5    143

[807 rows x 3 columns]

In [95]:
# selecting one column
df['weight']

type(df['weight'])

pandas.core.series.Series

In [96]:
# Filtering
# find the pokemon which attack is greater 100

df[df['attack'] > 100]

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
33,34,nidoking,1,1.4,62.0,227,poison,ground,81,102,77,85,85,75
56,57,primeape,1,1.0,32.0,159,fighting,NaN,65,105,60,95,60,70
58,59,arcanine,1,1.9,155.0,194,fire,NaN,90,110,80,95,100,80
67,68,machamp,1,1.6,130.0,227,fighting,NaN,90,130,80,55,65,85
70,71,victreebel,1,1.7,15.5,221,grass,poison,80,105,65,70,100,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,800,necrozma,7,2.4,230.0,270,psychic,NaN,97,107,101,79,127,89
801,802,marshadow,7,0.7,22.2,270,fighting,ghost,90,125,80,125,90,90
804,805,stakataka,7,5.5,820.0,257,rock,steel,61,131,211,13,53,101
805,806,blacephalon,7,1.8,13.0,257,fire,ghost,53,127,53,107,151,79
806,807,zeraora,7,1.5,44.5,270,electric,NaN,88,112,75,143,102,80

In [97]:
# Use filter in multiple column

df[
    (df['attack'] > 100)&
    (df['defense'] > 100)
]

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
75,76,golem,1,1.4,300.0,223,rock,ground,80,120,130,45,55,65
98,99,kingler,1,1.3,60.0,166,water,NaN,55,130,115,75,50,50
111,112,rhydon,1,1.9,120.0,170,ground,rock,105,130,120,40,45,45
140,141,kabutops,1,1.3,40.5,173,rock,water,60,115,105,80,65,70
231,232,donphan,2,1.1,120.0,175,ground,NaN,90,120,120,50,60,60
247,248,tyranitar,2,2.0,202.0,270,rock,dark,100,134,110,61,95,100
305,306,aggron,3,2.1,360.0,239,steel,rock,70,110,180,50,60,60
366,367,huntail,3,1.7,27.0,170,water,NaN,55,104,105,52,94,75
375,376,metagross,3,1.6,550.0,270,steel,psychic,80,135,130,70,95,90
382,383,groudon,3,3.5,950.0,302,ground,NaN,100,150,140,90,100,90
388,389,torterra,4,2.2,310.0,236,grass,ground,95,109,105,56,75,85
449,450,hippowdon,4,2.0,300.0,184,ground,NaN,108,112,118,47,68,72
463,464,rhyperior,4,2.4,282.8,241,ground,rock,115,140,130,40,55,55
469,470,leafeon,4,1.0,25.5,184,grass,NaN,65,110,130,95,60,65
480,481,mesprit,4,0.3,0.3,261,psychic,NaN,80,105,105,80,105,105
482,483,dialga,4,5.4,683.0,306,steel,dragon,100,120,120,90,150,100
485,486,regigigas,4,3.7,420.0,302,normal,NaN,110,160,110,100,80,110
492,493,arceus,4,3.2,320.0,324,normal,NaN,120,120,120,120,120,120
524,525,boldore,5,0.9,102.0,137,rock,NaN,70,105,105,20,50,40
525,526,gigalith,5,1.7,260.0,232,rock,NaN,85,135,130,25,60,80
557,558,crustle,5,1.4,200.0,170,bug,rock,70,105,125,45,65,75
564,565,carracosta,5,1.2,81.0,173,water,rock,74,108,133,32,83,65
588,589,escavalier,5,1.0,33.0,173,bug,steel,70,135,105,20,60,105
631,632,durant,5,0.3,33.0,169,bug,steel,58,109,112,109,48,48
643,644,zekrom,5,2.9,345.0,306,dragon,electric,100,150,120,90,120,100
651,652,chesnaught,6,1.6,90.0,239,grass,fighting,88,107,122,64,74,75
679,680,doublade,6,0.8,4.5,157,steel,ghost,59,110,150,35,45,49
688,689,barbaracle,6,1.3,96.0,175,rock,water,72,105,115,68,54,86
696,697,tyrantrum,6,2.5,270.0,182,rock,dragon,82,121,119,71,69,59
712,713,avalugg,6,2.0,505.0,180,ice,NaN,95,117,184,28,44,46
720,721,volcanion,6,1.7,195.0,270,fire,water,80,110,120,70,130,90
767,768,golisopod,7,2.0,108.0,186,bug,water,75,125,140,40,60,90
783,784,kommo-o,7,1.6,78.2,270,dragon,fighting,75,110,125,85,100,105
786,787,tapu-bulu,7,1.9,45.5,257,grass,fairy,70,130,115,75,85,95
790,791,solgaleo,7,3.4,230.0,306,psychic,steel,137,137,107,97,113,89
793,794,buzzwole,7,2.4,333.6,257,bug,fighting,107,139,139,79,53,53
796,797,celesteela,7,9.2,999.9,257,steel,flying,97,101,103,61,107,101
797,798,kartana,7,0.3,0.1,257,grass,steel,59,181,131,109,59,31
799,800,necrozma,7,2.4,230.0,270,psychic,NaN,97,107,101,79,127,89
804,805,stakataka,7,5.5,820.0,257,rock,steel,61,131,211,13,53,101

In [98]:
# find the categorical data
df[df['type_1'] == 'fire']

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
3,4,charmander,1,0.6,8.5,62,fire,NaN,39,52,43,65,60,50
4,5,charmeleon,1,1.1,19.0,142,fire,NaN,58,64,58,80,80,65
5,6,charizard,1,1.7,90.5,240,fire,flying,78,84,78,100,109,85
36,37,vulpix,1,0.6,9.9,60,fire,NaN,38,41,40,65,50,65
37,38,ninetales,1,1.1,19.9,177,fire,NaN,73,76,75,100,81,100
57,58,growlithe,1,0.7,19.0,70,fire,NaN,55,70,45,60,70,50
58,59,arcanine,1,1.9,155.0,194,fire,NaN,90,110,80,95,100,80
76,77,ponyta,1,1.0,30.0,82,fire,NaN,50,85,55,90,65,65
77,78,rapidash,1,1.7,95.0,175,fire,NaN,65,100,70,105,80,80
125,126,magmar,1,1.3,44.5,173,fire,NaN,65,95,57,93,100,85
135,136,flareon,1,0.9,25.0,184,fire,NaN,65,130,60,65,95,110
145,146,moltres,1,2.0,60.0,261,fire,flying,90,100,90,90,125,85
154,155,cyndaquil,2,0.5,7.9,62,fire,NaN,39,52,43,65,60,50
155,156,quilava,2,0.9,19.0,142,fire,NaN,58,64,58,80,80,65
156,157,typhlosion,2,1.7,79.5,240,fire,NaN,78,84,78,100,109,85
217,218,slugma,2,0.7,35.0,50,fire,NaN,40,40,40,20,70,40
218,219,magcargo,2,0.8,55.0,151,fire,rock,60,50,120,30,90,80
239,240,magby,2,0.7,21.4,73,fire,NaN,45,75,37,83,70,55
243,244,entei,2,2.1,198.0,261,fire,NaN,115,115,85,100,90,75
249,250,ho-oh,2,3.8,199.0,306,fire,flying,106,130,90,90,110,154
254,255,torchic,3,0.4,2.5,62,fire,NaN,45,60,40,45,70,50
255,256,combusken,3,0.9,19.5,142,fire,fighting,60,85,60,55,85,60
256,257,blaziken,3,1.9,52.0,239,fire,fighting,80,120,70,80,110,70
321,322,numel,3,0.7,24.0,61,fire,ground,60,60,40,35,65,45
322,323,camerupt,3,1.9,220.0,161,fire,ground,70,100,70,40,105,75
323,324,torkoal,3,0.5,80.4,165,fire,NaN,70,85,140,20,85,70
389,390,chimchar,4,0.5,6.2,62,fire,NaN,44,58,44,61,58,44
390,391,monferno,4,0.9,22.0,142,fire,fighting,64,78,52,81,78,52
391,392,infernape,4,1.2,55.0,240,fire,fighting,76,104,71,108,104,71
466,467,magmortar,4,1.6,68.0,243,fire,NaN,75,95,67,83,125,95
484,485,heatran,4,1.7,430.0,270,fire,steel,91,90,106,77,130,106
497,498,tepig,5,0.5,9.9,62,fire,NaN,65,63,45,45,45,45
498,499,pignite,5,1.0,55.5,146,fire,fighting,90,93,55,55,70,55
499,500,emboar,5,1.6,150.0,238,fire,fighting,110,123,65,65,100,65
512,513,pansear,5,0.6,11.0,63,fire,NaN,50,53,48,64,53,48
513,514,simisear,5,1.0,28.0,174,fire,NaN,75,98,63,101,98,63
553,554,darumaka,5,0.6,37.5,63,fire,NaN,70,90,45,50,15,45
554,555,darmanitan,5,1.3,92.9,168,fire,NaN,105,140,55,95,30,55
630,631,heatmor,5,1.4,58.0,169,fire,NaN,85,97,66,65,105,66
652,653,fennekin,6,0.4,9.4,61,fire,NaN,40,45,40,60,62,60
653,654,braixen,6,1.0,14.5,143,fire,NaN,59,59,58,73,90,70
654,655,delphox,6,1.5,39.0,240,fire,psychic,75,69,72,104,114,100
661,662,fletchinder,6,0.7,16.0,134,fire,flying,62,73,55,84,56,52
662,663,talonflame,6,1.2,24.5,175,fire,flying,78,81,71,126,74,69
666,667,litleo,6,0.6,13.5,74,fire,normal,62,50,58,72,73,54
667,668,pyroar,6,1.5,81.5,177,fire,normal,86,68,72,106,109,66
720,721,volcanion,6,1.7,195.0,270,fire,water,80,110,120,70,130,90
724,725,litten,7,0.4,4.3,64,fire,NaN,45,65,40,70,60,40
725,726,torracat,7,0.7,25.0,147,fire,NaN,65,85,50,90,80,50
726,727,incineroar,7,1.8,83.0,239,fire,dark,95,115,90,60,80,90
740,741,oricorio,7,0.6,3.4,167,fire,flying,75,70,70,93,98,70
775,776,turtonator,7,2.0,212.0,170,fire,dragon,60,78,135,36,91,85
805,806,blacephalon,7,1.8,13.0,257,fire,ghost,53,127,53,107,151,79

In [99]:
df[df['type_2'] == 'water']

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
137,138,omanyte,1,0.4,7.5,71,rock,water,35,40,100,35,90,55
138,139,omastar,1,1.0,35.0,173,rock,water,70,60,125,55,115,70
139,140,kabuto,1,0.5,11.5,71,rock,water,30,80,90,55,55,45
140,141,kabutops,1,1.3,40.5,173,rock,water,60,115,105,80,65,70
282,283,surskit,3,0.5,1.7,54,bug,water,40,30,32,65,50,52
362,363,spheal,3,0.8,39.5,58,ice,water,70,40,50,25,55,50
363,364,sealeo,3,1.1,87.6,144,ice,water,90,60,70,45,75,70
364,365,walrein,3,1.4,150.6,239,ice,water,110,80,90,65,95,90
399,400,bibarel,4,1.0,31.5,144,normal,water,79,85,60,71,55,60
687,688,binacle,6,0.5,31.0,61,rock,water,42,52,67,50,39,56
688,689,barbaracle,6,1.3,96.0,175,rock,water,72,105,115,68,54,86
689,690,skrelp,6,0.5,7.3,64,poison,water,50,60,60,30,60,60
720,721,volcanion,6,1.7,195.0,270,fire,water,80,110,120,70,130,90
746,747,mareanie,7,0.4,8.0,61,poison,water,50,53,62,45,43,52
747,748,toxapex,7,0.7,14.5,173,poison,water,50,63,152,35,53,142
766,767,wimpod,7,0.5,12.0,46,bug,water,25,35,40,80,20,30
767,768,golisopod,7,2.0,108.0,186,bug,water,75,125,140,40,60,90

In [100]:
# if we want multiple type fire OR Water
df[df['type_1'].isin(['water', 'fire'])]

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
3,4,charmander,1,0.6,8.5,62,fire,NaN,39,52,43,65,60,50
4,5,charmeleon,1,1.1,19.0,142,fire,NaN,58,64,58,80,80,65
5,6,charizard,1,1.7,90.5,240,fire,flying,78,84,78,100,109,85
6,7,squirtle,1,0.5,9.0,63,water,NaN,44,48,65,43,50,64
7,8,wartortle,1,1.0,22.5,142,water,NaN,59,63,80,58,65,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,771,pyukumuku,7,0.3,1.2,144,water,NaN,55,60,130,5,30,130
775,776,turtonator,7,2.0,212.0,170,fire,dragon,60,78,135,36,91,85
778,779,bruxish,7,0.9,19.0,166,water,psychic,68,105,70,92,70,70
787,788,tapu-fini,7,1.3,21.2,257,water,fairy,70,75,115,85,95,130
805,806,blacephalon,7,1.8,13.0,257,fire,ghost,53,127,53,107,151,79

In [101]:
# Sorting
# Find the strongest attacker

df.sort_values("attack", ascending=False)

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
797,798,kartana,7,0.3,0.1,257,grass,steel,59,181,131,109,59,31
408,409,rampardos,4,1.6,102.5,173,rock,NaN,97,165,60,58,65,50
288,289,slaking,3,2.0,130.5,252,normal,NaN,150,160,100,100,95,65
485,486,regigigas,4,3.7,420.0,302,normal,NaN,110,160,110,100,80,110
382,383,groudon,3,3.5,950.0,302,ground,NaN,100,150,140,90,100,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,blissey,2,1.5,46.8,608,normal,NaN,255,10,10,55,75,135
212,213,shuckle,2,0.6,20.5,177,bug,rock,20,10,230,5,10,230
128,129,magikarp,1,0.9,10.0,40,water,NaN,20,10,55,80,15,20
112,113,chansey,1,1.1,34.6,395,normal,NaN,250,5,5,50,35,105
439,440,happiny,4,0.6,24.4,110,normal,NaN,100,5,5,30,15,65

In [102]:
# If i want to find the  top 10 values
df.sort_values(
    "attack",
    ascending=False
).head(10)

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
797,798,kartana,7,0.3,0.1,257,grass,steel,59,181,131,109,59,31
408,409,rampardos,4,1.6,102.5,173,rock,NaN,97,165,60,58,65,50
288,289,slaking,3,2.0,130.5,252,normal,NaN,150,160,100,100,95,65
485,486,regigigas,4,3.7,420.0,302,normal,NaN,110,160,110,100,80,110
382,383,groudon,3,3.5,950.0,302,ground,NaN,100,150,140,90,100,90
383,384,rayquaza,3,7.0,206.5,306,dragon,flying,105,150,90,95,150,90
643,644,zekrom,5,2.9,345.0,306,dragon,electric,100,150,120,90,120,100
385,386,deoxys,3,1.7,60.8,270,psychic,NaN,50,150,50,150,150,50
611,612,haxorus,5,1.8,105.5,243,dragon,NaN,76,147,90,97,60,70
463,464,rhyperior,4,2.4,282.8,241,ground,rock,115,140,130,40,55,55

In [103]:
# Sort by multiple columns
df.sort_values(
    ["attack", "defense"],
    ascending=False
).head(5)

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
797,798,kartana,7,0.3,0.1,257,grass,steel,59,181,131,109,59,31
408,409,rampardos,4,1.6,102.5,173,rock,NaN,97,165,60,58,65,50
485,486,regigigas,4,3.7,420.0,302,normal,NaN,110,160,110,100,80,110
288,289,slaking,3,2.0,130.5,252,normal,NaN,150,160,100,100,95,65
382,383,groudon,3,3.5,950.0,302,ground,NaN,100,150,140,90,100,90

In [104]:
# Basic Statistics
df.describe()

,id,generation_id,height,weight,base_experience,hp,attack,defense,speed,special_attack,special_defense
count,807.000000,807.000000,807.000000,807.000000,807.000000,807.000000,807.000000,807.000000,807.000000,807.000000,807.000000
mean,404.000000,3.714994,1.162454,61.771128,144.848823,68.748451,76.086741,71.726146,65.830235,69.486989,70.013631
std,233.105126,1.944148,1.081030,111.519355,74.953116,26.032808,29.544598,29.730228,27.736838,29.439715,27.292344
min,1.000000,1.000000,0.100000,0.100000,36.000000,1.000000,5.000000,5.000000,5.000000,10.000000,20.000000
25%,202.500000,2.000000,0.600000,9.000000,66.000000,50.000000,55.000000,50.000000,45.000000,45.000000,50.000000
50%,404.000000,4.000000,1.000000,27.000000,151.000000,65.000000,75.000000,67.000000,65.000000,65.000000,65.000000
75%,605.500000,5.000000,1.500000,63.000000,179.500000,80.000000,95.000000,89.000000,85.000000,90.000000,85.000000
max,807.000000,7.000000,14.500000,999.900000,608.000000,255.000000,181.000000,230.000000,160.000000,173.000000,230.000000

In [105]:
df['attack'].mean()
df['attack'].median()
df['attack'].min()
df['attack'].max()
df['attack'].std()
df['attack'].describe()

count    807.000000
mean      76.086741
std       29.544598
min        5.000000
25%       55.000000
50%       75.000000
75%       95.000000
max      181.000000
Name: attack, dtype: float64

In [106]:
df.shape

(807, 14)

In [107]:
df.sort_values(
    'defense',
    ascending=False
).head(10)

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
212,213,shuckle,2,0.6,20.5,177,bug,rock,20,10,230,5,10,230
804,805,stakataka,7,5.5,820.0,257,rock,steel,61,131,211,13,53,101
207,208,steelix,2,9.2,400.0,179,steel,ground,75,85,200,30,55,65
376,377,regirock,3,1.7,230.0,261,rock,NaN,80,100,200,50,50,100
712,713,avalugg,6,2.0,505.0,180,ice,NaN,95,117,184,28,44,46
90,91,cloyster,1,1.5,132.5,184,water,ice,50,95,180,70,85,45
305,306,aggron,3,2.1,360.0,239,steel,rock,70,110,180,50,60,60
410,411,bastiodon,4,1.3,149.5,173,rock,steel,60,52,168,30,47,138
94,95,onix,1,8.8,210.0,77,rock,ground,35,45,160,70,30,45
747,748,toxapex,7,0.7,14.5,173,poison,water,50,63,152,35,53,142

In [108]:
# Pokemon with the highest attack
highest_attack = df.loc[df['attack'].idxmax()]

print("Species:", highest_attack['species'])
print("Attack:", highest_attack['attack'])
print()

Species: kartana
Attack: 181

In [109]:
# Pokemon with the highest defense
highest_defense = df.loc[df['defense'].idxmax()]

print("Species:", highest_defense['species'])
print("Defense:", highest_defense['defense'])

Species: shuckle
Defense: 230

In [110]:
# Top 10 pokemon by defense
top_10_def = df.sort_values(
    'defense',
    ascending=False
).head(10)

print(top_10_def[['species', 'defense']])

       species  defense
212    shuckle      230
804  stakataka      211
207    steelix      200
376   regirock      200
712    avalugg      184
90    cloyster      180
305     aggron      180
410  bastiodon      168
94        onix      160
747    toxapex      152

In [111]:
# Pokemon HP where is 100
high_hp = df[df['hp'] > 100]
print(high_hp)

      id     species  generation_id  height  weight  base_experience   type_1  \
38    39  jigglypuff              1     0.5     5.5               95   normal
39    40  wigglytuff              1     1.0    12.0              196   normal
88    89         muk              1     1.2    30.0              175   poison
111  112      rhydon              1     1.9   120.0              170   ground
112  113     chansey              1     1.1    34.6              395   normal
..   ...         ...            ...     ...     ...              ...      ...
790  791    solgaleo              7     3.4   230.0              306  psychic
791  792      lunala              7     4.0   120.0              306  psychic
792  793    nihilego              7     1.2    55.5              257     rock
793  794    buzzwole              7     2.4   333.6              257      bug
798  799    guzzlord              7     5.5   888.0              257     dark

       type_2   hp  attack  defense  speed  special_attack  special_defense
38      fairy  115      45       20     20              45               25
39      fairy  140      70       45     45              85               50
88        NaN  105     105       75     50              65              100
111      rock  105     130      120     40              45               45
112       NaN  250       5        5     50              35              105
..        ...  ...     ...      ...    ...             ...              ...
790     steel  137     137      107     97             113               89
791     ghost  137     113       89     97             137              107
792    poison  109      53       47    103             127              131
793  fighting  107     139      139     79              53               53
798    dragon  223     101       53     43              97               53

[63 rows x 14 columns]

In [112]:
# fire type pokemon with attack 100
df_and_operation = df[
    (df['type_1'] == 'fire')&
    (df['attack'] > 100)
]

print(df_and_operation[['species', 'type_1', 'attack']])

         species type_1  attack
58      arcanine   fire     110
135      flareon   fire     130
243        entei   fire     115
249        ho-oh   fire     130
256     blaziken   fire     120
391    infernape   fire     104
499       emboar   fire     123
554   darmanitan   fire     140
720    volcanion   fire     110
726   incineroar   fire     115
805  blacephalon   fire     127

In [113]:
# Number of pokemon type_1

Value = df['type_1'].value_counts()
Value

type_1
water       114
normal      105
grass        78
bug          72
fire         53
psychic      53
rock         46
electric     40
poison       34
ground       32
dark         29
fighting     29
ghost        27
dragon       27
steel        24
ice          23
fairy        18
flying        3
Name: count, dtype: int64

In [114]:
# Number of Pokemon by generation
generation_count = df['generation_id'].value_counts().sort_index()
generation_count

generation_id
1    151
2    100
3    135
4    107
5    156
6     72
7     86
Name: count, dtype: int64

In [115]:

df.head()

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense
0,1,bulbasaur,1,0.7,6.9,64,grass,poison,45,49,49,45,65,65
1,2,ivysaur,1,1.0,13.0,142,grass,poison,60,62,63,60,80,80
2,3,venusaur,1,2.0,100.0,236,grass,poison,80,82,83,80,100,100
3,4,charmander,1,0.6,8.5,62,fire,NaN,39,52,43,65,60,50
4,5,charmeleon,1,1.1,19.0,142,fire,NaN,58,64,58,80,80,65

In [116]:
# create total stats
df["sachin_bist"] = (
    df["hp"]
    + df["attack"]
    + df["defense"]
    + df["speed"]
    + df["special_attack"]
    + df["special_defense"]
)

print(
    df[
        ["species",
        "hp",
        "attack",
        "defense",
        "speed",
        "special_attack",
        "special_defense",
        "sachin_bist"]
    ].head()
)

      species  hp  attack  defense  speed  special_attack  special_defense  \
0   bulbasaur  45      49       49     45              65               65
1     ivysaur  60      62       63     60              80               80
2    venusaur  80      82       83     80             100              100
3  charmander  39      52       43     65              60               50
4  charmeleon  58      64       58     80              80               65

   sachin_bist
0          318
1          405
2          525
3          309
4          405

In [117]:
top_10_total = (
    df.sort_values("sachin_bist", ascending=False).head(10)
)
print(top_10_total[["species", "sachin_bist"]])

      species  sachin_bist
492    arceus          720
149    mewtwo          680
716   yveltal          680
483    palkia          680
482    dialga          680
790  solgaleo          680
791    lunala          680
383  rayquaza          680
642  reshiram          680
643    zekrom          680

In [118]:
stat_column = [
    "hp",
    "attack",
    "speed",
    "defense",
    "special_attack",
    "special_defense"
]

df["sachin_bista"] = df[stat_column].sum(axis=1)
df.head()

,id,species,generation_id,height,weight,base_experience,type_1,type_2,hp,attack,defense,speed,special_attack,special_defense,sachin_bist,sachin_bista
0,1,bulbasaur,1,0.7,6.9,64,grass,poison,45,49,49,45,65,65,318,318
1,2,ivysaur,1,1.0,13.0,142,grass,poison,60,62,63,60,80,80,405,405
2,3,venusaur,1,2.0,100.0,236,grass,poison,80,82,83,80,100,100,525,525
3,4,charmander,1,0.6,8.5,62,fire,NaN,39,52,43,65,60,50,309,309
4,5,charmeleon,1,1.1,19.0,142,fire,NaN,58,64,58,80,80,65,405,405

In [119]:
# delete the column

df = df.drop(columns=["total_stats"])
df.head()

KeyError: "['total_stats'] not found in axis"

In [ ]:
lowest_attack = df.loc[df['attack'].idxmin()]
print(lowest_attack[['species', 'attack']])

species    chansey
attack           5
Name: 112, dtype: object

In [ ]:
# find the missing value

df.isnull().sum()

id                   0
species              0
generation_id        0
height               0
weight               0
base_experience      0
type_1               0
type_2             402
hp                   0
attack               0
defense              0
speed                0
special_attack       0
special_defense      0
sachin_bista         0
dtype: int64

In [ ]:
# Find the percentage of missing value
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

id                  0.000000
species             0.000000
generation_id       0.000000
height              0.000000
weight              0.000000
base_experience     0.000000
type_1              0.000000
type_2             49.814126
hp                  0.000000
attack              0.000000
defense             0.000000
speed               0.000000
special_attack      0.000000
special_defense     0.000000
sachin_bista        0.000000
dtype: float64

In [ ]:
# Only show the column that contain missing value
missing = df.isnull().sum()
print(missing[missing > 0])

type_2    402
dtype: int64

In [ ]:
# fill NA with None
df['type_2'] = df['type_2'].fillna("None")
df['type_2']

0      poison
1      poison
2      poison
3        None
4        None
        ...
802      None
803    dragon
804     steel
805     ghost
806      None
Name: type_2, Length: 807, dtype: object

In [ ]:
# Find out the duplicate records
df.duplicated().sum()

0

In [ ]:
df.duplicated(
    subset=['species']
).sum()

0

In [ ]:
df.dtypes

id                   int64
species             object
generation_id        int64
height             float64
weight             float64
base_experience      int64
type_1              object
type_2              object
hp                   int64
attack               int64
defense              int64
speed                int64
special_attack       int64
special_defense      int64
sachin_bista         int64
dtype: object