In [2]:
import pandas as pd

df = pd.read_csv('GOOG.csv')
df.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1  2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2  2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3  2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4  2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [9]:
# We load the Google stock data into a DataFrame
google_stock = pd.read_csv('GOOG.csv', index_col = ['Date'], parse_dates = True, usecols = ['Date', 'Adj Close'])

# We load the Apple stock data into a DataFrame
apple_stock = pd.read_csv('AAPL.csv', index_col = ['Date'], parse_dates = True, usecols = ['Date', 'Adj Close'])

# We load the Amazon stock data into a DataFrame
amazon_stock = pd.read_csv('AMZN.csv',index_col = ['Date'], parse_dates = True, usecols = ['Date', 'Adj Close'])

In [10]:
google_stock.head(5)

            Adj Close
Date
2004-08-19  49.845802
2004-08-20  53.805050
2004-08-23  54.346527
2004-08-24  52.096165
2004-08-25  52.657513

In [12]:
# We create calendar dates between '2000-01-01' and  '2016-12-31'
dates = pd.date_range('2000-01-01', '2016-12-31')

# We create and empty DataFrame that uses the above dates as indices
all_stocks = pd.DataFrame(index=dates)

In [14]:
# We display the google_stock DataFrame
google_stock.head()

            Adj Close
Date
2004-08-19  49.845802
2004-08-20  53.805050
2004-08-23  54.346527
2004-08-24  52.096165
2004-08-25  52.657513

In [19]:
# We join the Google stock to all_stocks
all_stocks = all_stocks.join(google_stock, rsuffix='google')

# We join the Apple stock to all_stocks
all_stocks = all_stocks.join(apple_stock, rsuffix='apple')

# We join the Amazon stock to all_stocks
all_stocks = all_stocks.join(amazon_stock, rsuffix='amazom')

In [21]:
all_stocks.head()

,Adj Close,Adj Closegoogle,Adj Closegoogle,Adj Closeapple,Adj Closeamazom
2000-01-01,NaN,NaN,NaN,NaN,NaN
2000-01-02,NaN,NaN,NaN,NaN,NaN
2000-01-03,NaN,NaN,NaN,3.596616,89.3750
2000-01-04,NaN,NaN,NaN,3.293384,81.9375
2000-01-05,NaN,NaN,NaN,3.341579,69.7500

In [22]:
all_stocks.describe()

,Adj Close,Adj Closegoogle,Adj Closegoogle,Adj Closeapple,Adj Closeamazom
count,3115.000000,3115.000000,3115.000000,4277.000000,4277.000000
mean,347.420229,347.420229,347.420229,35.222976,166.095436
std,187.671596,187.671596,187.671596,37.945557,189.212345
min,49.681866,49.681866,49.681866,0.843106,5.970000
25%,220.088539,220.088539,220.088539,3.221090,38.009998
50%,286.397247,286.397247,286.397247,17.524017,76.980003
75%,508.255340,508.255340,508.255340,64.533600,243.919998
max,813.109985,813.109985,813.109985,126.941574,844.359985

In [23]:
# Print the column-wise count of NaN values, if any, in the all_stocks dataframe
all_stocks.isnull().sum()

Adj Close          3095
Adj Closegoogle    3095
Adj Closegoogle    3095
Adj Closeapple     1933
Adj Closeamazom    1933
dtype: int64

In [24]:
# Remove any rows that contain NaN values. Do this operation inplace. 
all_stocks.dropna(axis=0, inplace=True)

In [25]:
# Print the average stock price for each stock
print('The average stock price for each stock is: \n', all_stocks.mean(), '\n')
# Note: You can get the same result by printing it individually one-by-one as `all_stocks['Google'].mean()`

# Print the median stock price for each stock
print('The median stock price for each stock is: \n', all_stocks.median(), '\n')

# Print the standard deviation of the stock price for each stock  
print('The standard deviation of the stock price for each stock  is: \n', all_stocks.std(), '\n')

# Print the correlation between stocks
print('The correlation between stocks is: \n', all_stocks.corr(), '\n')

The average stock price for each stock is:
 Adj Close          347.420229
Adj Closegoogle    347.420229
Adj Closegoogle    347.420229
Adj Closeapple      47.736018
Adj Closeamazom    216.598177
dtype: float64

The median stock price for each stock is:
 Adj Close          286.397247
Adj Closegoogle    286.397247
Adj Closegoogle    286.397247
Adj Closeapple      39.461483
Adj Closeamazom    161.820007
dtype: float64

The standard deviation of the stock price for each stock  is:
 Adj Close          187.671596
Adj Closegoogle    187.671596
Adj Closegoogle    187.671596
Adj Closeapple      37.421555
Adj Closeamazom    199.129792
dtype: float64

The correlation between stocks is:
                  Adj Close  Adj Closegoogle  Adj Closegoogle  Adj Closeapple  \
Adj Close         1.000000         1.000000         1.000000        0.900242
Adj Closegoogle   1.000000         1.000000         1.000000        0.900242
Adj Closegoogle   1.000000         1.000000         1.000000        0.900242
Adj Closeapple    0.900242         0.900242         0.900242        1.000000
Adj Closeamazom   0.952444         0.952444         0.952444        0.886321

                 Adj Closeamazom
Adj Close               0.952444
Adj Closegoogle         0.952444
Adj Closegoogle         0.952444
Adj Closeapple          0.886321
Adj Closeamazom         1.000000

In [27]:
# We compute the rolling mean using a 150-Day window for Google stock
rollingMean = all_stocks['Adj Closegoogle'].rolling(150).mean()
rollingMean

            Adj Closegoogle  Adj Closegoogle
2004-08-19              NaN              NaN
2004-08-20              NaN              NaN
2004-08-23              NaN              NaN
2004-08-24              NaN              NaN
2004-08-25              NaN              NaN
...                     ...              ...
2016-12-23       758.236666       758.236666
2016-12-27       758.713066       758.713066
2016-12-28       759.111599       759.111599
2016-12-29       759.502732       759.502732
2016-12-30       759.763799       759.763799

[3115 rows x 2 columns]